require("core.plugin_config.colourscheme")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.lualine")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.lsp")
require("core.plugin_config.completions")
require("core.plugin_config.vimtex")
